### PR TITLE
Honeypot Shader packs Overhaul

### PR DESCRIPTION
**Pull request by AgiShark**
After a lot of trial and error and research with the `NX98304`, we have gained enough knowledge to build more correct and better shader packs
Based on that knowledge, overhauled the existing shader packs

### hsstandardshaders_for_ph :  

- Existing shaders are also likely created in a linear color space But I made sure this shader pack was built in a linear color space 
- By setting #pragma target 3.5, it is optimized to generate only shader variants suitable for the target system (DX11+)
- Because it is the pack of shaders that have been used the most and will be used the most in the future, We tried to include enough shader variants to avoid missing a meaningful shader variant in the game

### roy12_honeypot : 

- Built in a linear color space 
- Reduced file size by choosing more reasonable stripping options

### glass_honeypot  : 

- Built in a linear color space
- Reduced file size by choosing more reasonable stripping options

### fur_honeypot   : 

- Built in a linear color space 
- Reduced file size by choosing more reasonable stripping options

### extra_honeypot : 

- Built in a linear color space
- Reduced file size by choosing more reasonable stripping options

### vfx_honeypot  :   

- Built in a linear color space
- Reduced file size by choosing more reasonable stripping options
- Added 6 `Water and Caustic` shaders and built in a linear color space
- *Removed` FX/Gem shader`. This shader needs to be added back from `NX98304`
- *`FX/Gem_SubColor`, `FX/GemNoTransp`, `FX/GemNoTranspSubColor` shaders need to be added back from `NX98304`
- *`Advanced Water` shader needs to be added back from `NX98304`

### alloy_honeypot : 

- Built in a linear color space
- more reasonable stripping options
- By setting #pragma target 3.5, it is optimized to generate only shader variants suitable for the target system (DX11+)
- Replaced existing Alloy shaders with version `3.3.5` to be more in line with the version of Alloy Shader Framework used by HS modders
- Removed `Alloy/Decal/Additive`, `Alloy/Decal/Ambient`, `Alloy/Decal/Multiplicative`, `Alloy/Transmission/OneSided (Forward)`, `Alloy/Transmission/TwoSided (Forward)`
- Since these shaders have too many keywords options to choose from, only some frequently used keywords were selected to generate Shader variants

### lux_honeypot  :  

- Built in a linear color space
- more reasonable stripping options          
- By setting #pragma target 3.5, it is optimized to generate only shader variants suitable for the target system (DX11+)
- Since these shaders have too many keywords options to choose from, only some frequently used keywords were selected to generate Shader variants    

 

### uber_honeypot : 

- Built in a linear color space
- more reasonable stripping options          
- By setting #pragma target 3.5, it is optimized to generate only shader variants suitable for the target system (DX11+)
- Since these shaders have too many keywords options to choose from, only some frequently used keywords were selected to generate Shader variants

### CODE REVIEW

**Comment by AgiShark** [comment]
I've tested some HS mods with these shader packs and haven't found any issues yet.
but surely, I haven't tested enough because there are too many shaders to test.
If you find any issues, let me know 👍

**Comment by AgiShark** [comment]
Pre-OverHaul timestamps on my box

[Info   :   Console] Shader loaded timestamp: 2568
[Info   :   Console] List GetFiles timestamp: 2575
[Info   :   Console] List crawled timestamp: 2588
[Info   :   Console] Inspector established timestamp: 4285
[Info   :   Console] Dynamic Harmony patches timestamp: 4297
[Info   :   Console] All shader prepared - HoneyPot first run used time: 4298


After-Overhaul V1(PR version) timestamps on my box 

[Info   :   Console] Shader loaded timestamp: 2257
[Info   :   Console] List GetFiles timestamp: 2263
[Info   :   Console] List crawled timestamp: 2274
[Info   :   Console] Inspector established timestamp: 3994
[Info   :   Console] Dynamic Harmony patches timestamp: 4007
[Info   :   Console] All shader prepared - HoneyPot first run used time: 4007


After-OverHaul V2 (current version) timestamps on my box  

- Removed the` multi_compile DIRLIGHTMAP_COMBINED` in Standard_555,ticked both Baked `Non-Direct` and `Direct` 
- Unticked all stripping options for 4 Hsstandard shaders and manually added these 4 shaders to hsstandardshaders_for_ph
- hsstandardshaders_for_ph 9.6MB -> 7.5MB
- Set #pragma target 3.5 on roy12,glass,fur,vfx,extra shader pack) 

[Info   :   Console] Shader loaded timestamp: 2183
[Info   :   Console] List GetFiles timestamp: 2189
[Info   :   Console] List crawled timestamp: 2204
[Info   :   Console] Inspector established timestamp: 3911
[Info   :   Console] Dynamic Harmony patches timestamp: 3930
[Info   :   Console] All shader prepared - HoneyPot first run used time: 3930

**Comment by AgiShark** [comment]
Additional findings
About the navy swimsuit was expressed as a gray swimsuit in the Unity editor.
When the main texture of the swimsuit was exported from SB3U, the texture was exported as a .dds file, and when it was directly imported into unity, the texture was set to linear. However, the Main color tex should be set to Gamma. Since the dds file cannot be flagged linear->sRGB in Unity, I saved the dds file as TGA in Photoshop and imported the texture in Unity. Then, when I set the texture with sRGB and assign it to the albedo slot of the standard shader, it was confirmed that the navy color was expressed as intended.

**Comment by AgiShark** [comment]
The millisecond difference between V1 and the current test version V2 doesn't seem to make much of a difference on my box, so I don't plan to push V2 unless there are other issues.

**Comment by AgiShark** [comment]
Found the need to modify Shader pack Prefabs to be Material Editor friendly. Working on it.

**Comment by nx98304** [comment]
Thank you AgiShark again, and sorry for the delay (due to IRL stuff!)

**Pull request merged**
